// Website knowledge, kept explicit so the assistant never invents prices or availability.
export type ChatAnswer = { text: string; href?: string; label?: string; topic?: string; handoff?: boolean };
export type ChatCatalog = { cities: {name:string;slug:string}[]; trades: {name:string;name_singular:string;slug_plural:string;active:boolean}[] };
const normal = (text: string) => text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const has = (text: string, pattern: RegExp) => pattern.test(text);
export function answerQuestion(question: string, catalog: ChatCatalog, previousTopic?: string): ChatAnswer {
 const q=normal(question).replace(/\b(reservate|reservaton|reservez|reservationn)\b/g, "reserver").replace(/\b(facturr?e|facturre)\b/g,"facture");
 const platformAnswer = answerPlatformQuestion(q, previousTopic);
 if (platformAnswer) return platformAnswer;
 const handoff: ChatAnswer={text:"Je préfère vous orienter vers l’équipe LaMain2 pour vous donner une réponse fiable. Laissez votre nom et votre email ; vous pourrez aussi ajouter un téléphone pour être rappelé.",handoff:true,topic:"contact"};
 if(has(q,/\b(gaz|gas|incendie|electrocution|danger immediat)\b/)) return {text:"Si vous suspectez un danger immédiat, mettez-vous en sécurité et contactez les secours. Ce chat ne remplace pas un service d’urgence.",handoff:true,topic:"safety"};
 if(has(q,/\b(humain|personne|conseiller|rappel|rappeler|callback|human|reclamation|plainte|rembours[a-z]*|litige|garantie|assurance)\b/) || has(q,/parler.*(quelqu|equipe|responsable)/)) return handoff;
 if(has(q,/\b(email|mail|telephone|numero|phone)\b/) && has(q,/\b(artisan|plombier|electricien)\b/)) return {text:"Le téléphone de l’artisan est visible sur son profil lorsqu’il est renseigné. Son email reste privé. Ouvrez sa fiche pour l’appeler ou réserver.",href:"/recherche",label:"Trouver son profil",topic:"contact-artisan"};
 if(has(q,/\b(sans (?:creer (?:un |de )?)?compte|sans inscription|sans connexion|sans login|guest|without.*account)\b/)) return {text:"Oui, vous pouvez réserver sans créer de compte. Sur la page de réservation, choisissez de continuer sans connexion, puis indiquez vos coordonnées et les détails de l’intervention. Votre confirmation permet de retrouver votre demande.",href:"/recherche",label:"Choisir un artisan",topic:"guest"};
 if(has(q,/\b(annul|annuler|annulation|modifier|deplacer|cancel|reschedul)/)) return {text:"Avec un compte, retrouvez la réservation dans votre espace client pour l’annuler. Pour changer l’intervention, contactez l’artisan. Si vous avez réservé sans compte, utilisez votre confirmation pour retrouver la demande ; l’équipe peut vous aider si vous ne la retrouvez pas.",href:"/mes-reservations",label:"Mes réservations",topic:"cancellation"};
 if(has(q,/\b(facture|factures|invoice|devis|quote)\b/) && (has(q,/\b(creer|generer|pdf|compte|artisan|download|create|telecharger)\b/) || previousTopic==="professional" || previousTopic==="documents")) return {text:"Les artisans disposent d’un onglet « Devis et factures » dans leur compte. Ajoutez le client, les prestations et leurs prix, choisissez les dates et le mode de paiement, puis générez un PDF prêt à télécharger. Les coordonnées de votre entreprise sont reprises depuis votre profil.",href:"/devis-factures",label:"Devis et factures",topic:"documents"};
 if(has(q,/\b(devenir|inscrire|inscription|partenaire|abonnement|join)\b/) && has(q,/\b(artisan|professionnel|plombier|electricien|partner)\b/)) return {text:"Créez votre compte artisan, renseignez votre activité et complétez votre dossier. L’équipe vérifie les informations avant l’activation. Votre espace permet ensuite de consulter les deux services attribués, gérer le calendrier, les réservations, les devis et les factures. Pour les conditions d’abonnement, demandez une réponse personnelle à l’équipe.",href:"/inscription/professionnel",label:"Devenir artisan",topic:"professional"};
 if(has(q,/\b(payer|paiement|carte|virement|cash|cheque|payment|pay)\b/)) return {text:"Le paiement de l’intervention se règle directement avec l’artisan. LaMain2 vous permet de rechercher et réserver ; vérifiez avec le professionnel les moyens de paiement qu’il accepte.",href:"/recherche",label:"Voir les artisans",topic:"payment"};
 if(has(q,/\b(prix|tarif|tarifs|cout|coute|combien|gratuit|commission|price|cost|devis)\b/)) return {text:"La recherche et la réservation sont gratuites pour les clients, sans commission sur l’intervention. Les prix ou la mention « Sur devis » figurent sur les services du profil artisan. Le montant dépend de la prestation : je ne peux pas vous promettre un prix sans ces détails.",href:"/recherche",label:"Comparer les artisans",topic:"pricing"};
 if(has(q,/\b(horaire|horaires|disponible|disponibilites?|heure|ouvert|ferme|hours|available)\b/)) return {text:"Les horaires habituels sont affichés sur le profil de chaque artisan lorsqu’ils sont renseignés. Cliquez sur « Réserver » pour consulter les créneaux proposés. Les horaires habituels ne garantissent pas qu’un créneau est encore libre.",href:"/recherche",label:"Voir les profils et horaires",topic:"hours"};
 if(has(q,/\b(avis|google|review|reviews|note|verifie|fiable|confiance)\b/)) return {text:"Les résultats affichent la note et le nombre d’avis Google renseignés pour chaque artisan. Son profil présente aussi les avis LaMain2 et un accès à Google Maps pour laisser un avis. Le dossier de l’artisan est vérifié avant l’activation.",href:"/recherche",label:"Consulter les profils",topic:"reviews"};
 if(has(q,/\b(mot de passe|password|connexion|connecter|login|compte|account)\b/)) return {text:"Vous pouvez créer un compte client pour retrouver vos réservations, ou réserver sans connexion. Si vous avez oublié votre mot de passe, utilisez le lien de réinitialisation sur la page de connexion.",href:"/connexion",label:"Accéder à mon compte",topic:"account"};
 if(has(q,/\b(confidentialite|donnee|donnees|cookie|privacy|email prive)\b/)) return {text:"Les emails des artisans ne sont pas affichés publiquement. Pour une réponse personnelle dans ce chat, vos coordonnées et la conversation sont envoyées à l’équipe LaMain2 uniquement après votre accord.",href:"/confidentialite",label:"Politique de confidentialité",topic:"privacy"};
 const city=catalog.cities.find(c=>(" "+q+" ").includes(" "+normal(c.name)+" "));
 const trade=catalog.trades.find(t=>q.includes(normal(t.name_singular)) || q.includes(normal(t.name)) || (t.slug_plural==="plombiers" && has(q,/\b(fuite|debouchage|plumbing|plumber)\b/)) || (t.slug_plural==="electriciens" && has(q,/\b(electricite|electrician)\b/)));
 if(trade && !trade.active) return {text:trade.name+" n’est pas encore proposé à la réservation sur LaMain2. L’équipe peut vous renseigner sur votre besoin.",handoff:true,topic:"search"};
 if(city || trade || has(q,/\b(comment ca marche|fonctionne|chercher|rechercher|trouver|reservation|reserver|book|booking|urgence|urgent)\b/)) {
  const params=new URLSearchParams();if(city)params.set("ville",city.slug);if(trade?.active)params.set("metier",trade.slug_plural);
  return {text:city ? "Voici la recherche pour "+city.name+(trade?" en "+trade.name.toLowerCase():"")+". Comparez les profils, choisissez un service puis un créneau. Les résultats vous indiqueront quels artisans interviennent dans ce secteur." : "Indiquez votre ville et votre métier sur la recherche, comparez les profils puis choisissez une prestation et un créneau. Vous pourrez réserver avec ou sans compte.",href:"/recherche"+(params.size?"?"+params.toString():""),label:city?"Voir les artisans à "+city.name:"Rechercher un artisan",topic:"search"};
 }
 if(has(q,/^(bonjour|bonsoir|salut|hello|hi|coucou)$/)) return {text:"Bonjour ! Je suis l’assistant automatique de LaMain2. Vous cherchez un artisan, des informations sur une réservation ou une aide pour votre compte ?",topic:"greeting"};
 if(has(q,/^(merci|merci beaucoup|thanks|thank you|ok|parfait)$/)) return {text:"Avec plaisir ! Vous pouvez me poser une autre question ou demander une réponse personnelle à l’équipe.",topic:previousTopic};
 if(has(q,/^(et sans compte|et sans inscription)$/)) return answerQuestion("sans compte",catalog);
 return handoff;
}

// Public product facts only. Each entry names its source so changes can be reviewed
// against the actual feature; no customer records, private emails or invented terms.
type PlatformRule = { topic: string; match: RegExp; text: string; href?: string; label?: string; source: string };
const PLATFORM_RULES: PlatformRule[] = [
 {topic:"platform", match:/\b(lamain2|la main 2|plan b|plateforme|platform|site)\b.*\b(c est quoi|quoi|fonctionne|marche|propose|proposez)\b|\b(qui etes vous|c est quoi lamain2|what is)\b/, text:"LaMain2 met en relation les clients et les artisans. Choisissez votre ville et votre métier, comparez les profils, puis réservez avec ou sans compte. Vous échangez directement avec le professionnel et réglez l’intervention avec lui.",href:"/recherche",label:"Trouver un artisan",source:"app/(public)/page.tsx"},
 {topic:"services", match:/\b(services?|prestations?)\b.*\b(ajouter|supprimer|modifier|editer|deux|2|propose|proposes|disponibles)\b|\b(ajouter|supprimer|modifier|editer)\b.*\b(services?|prestations?)\b|\b(service urgent|intervention classique|service particulier)\b/,text:"Chaque artisan reçoit automatiquement deux services : « Service urgent » et « Intervention classique ». Les descriptions dépendent du métier. L’artisan ne peut pas ajouter, supprimer ou modifier ces services depuis son compte. Consultez son profil pour le prix affiché ou la mention « Sur devis ».",href:"/recherche",label:"Consulter les services",source:"lib/professional/default-plumbing-services.ts; components/professional/services-manager.tsx"},
 {topic:"calendar",match:/\b(changer|modifier|gerer|regler|mettre|configurer)\b.*\b(horaires?|calendrier|disponibilites?|creneaux?)\b|\b(calendrier|mes horaires)\b/,text:"Dans votre compte artisan, ouvrez « Calendrier » pour gérer vos créneaux et horaires. Les horaires par défaut sont 10h–20h tous les jours ; vous pouvez les adapter. Pour remplacer un horaire, retirez l’ancien puis ajoutez le nouveau. Retirer les plages d’un jour le rend fermé. Les clients voient vos horaires sur votre profil ; un horaire d’ouverture ne garantit pas une place libre.",href:"/calendrier",label:"Mon calendrier",source:"app/(professional)/calendrier/page.tsx"},
 {topic:"profile",match:/\b(mon profil|ma fiche|mes photos|ma photo|mes coordonnees|zone d intervention|zones d intervention)\b|\b(changer|modifier|ajouter)\b.*\b(photo|adresse|telephone|description|ville)\b/,text:"Dans « Mon profil », vous pouvez mettre à jour votre présentation, vos coordonnées, votre photo et vos zones d’intervention. Ajoutez jusqu’à six photos de réalisations : elles apparaissent dans le carrousel du profil. L’adresse et le téléphone renseignés sont publics ; l’email de contact reste privé.",href:"/profil",label:"Mon profil artisan",source:"app/(professional)/profil/page.tsx"},
 {topic:"verification",match:/\b(document|documents|justificatif|justificatifs|verification|activation|activer|siret|identite|qualification)\b/,text:"L’inscription artisan comprend un dossier à vérifier avant activation. L’onglet « Documents » permet d’envoyer vos justificatifs : identité, qualification, assurance ou autre document. Ces fichiers sont privés, accessibles à vous et à l’équipe de vérification. Pour connaître l’avancement précis de votre dossier, demandez une réponse personnelle à l’équipe ; le chat n’a pas accès à votre compte.",href:"/documents",label:"Mes documents",source:"app/(professional)/documents/page.tsx"},
 {topic:"notifications",match:/\b(whatsapp|sms|notification|notifications|confirmation|confirmer|email de reservation|mail de reservation)\b/,text:"Après votre réservation, conservez la page de confirmation et votre référence. L’envoi des emails dépend du bon fonctionnement du service de messagerie : je ne peux pas vérifier leur réception ici. Lorsque le téléphone de l’artisan est renseigné, la confirmation propose aussi un bouton WhatsApp avec les détails de la demande. Il ouvre un message préparé : vous devez appuyer sur Envoyer, et l’artisan doit utiliser WhatsApp. Les SMS ne sont actuellement pas activés.",href:"/contact",label:"Aide pour ma confirmation",source:"app/(public)/reservation-confirmee/[bookingNumber]/page.tsx; lib/booking/whatsapp.ts"},
 {topic:"booking-details",match:/\b(photos?|informations?|coordonnees|details)\b.*\b(reservation|reserver|demande|intervention)\b|\b(que remplir|quoi remplir)\b/,text:"Pour réserver, choisissez l’artisan et son service, puis indiquez vos coordonnées, l’adresse d’intervention et une description du besoin. Vous pouvez joindre des photos. Selon le service, choisissez un créneau ou envoyez une demande de devis. Vérifiez les informations avant de valider. Vous pouvez continuer sans compte ou vous connecter.",href:"/recherche",label:"Préparer ma réservation",source:"components/booking"},
 {topic:"professional-bookings",match:/\b(mes reservations|mes demandes|accepter|refuser|terminer|interventions)\b.*\b(artisan|professionnel|client|clients)\b|\b(reservations artisan|demandes clients)\b/,text:"Dans votre espace artisan, l’onglet « Réservations » regroupe les demandes. Ouvrez une demande pour consulter les informations du client et les détails de l’intervention, puis utilisez les actions disponibles selon son statut. Le chat ne peut pas accepter une demande ni consulter vos réservations privées.",href:"/reservations",label:"Mes réservations artisan",source:"app/(professional)/reservations/[id]/page.tsx"},
 {topic:"account-security",match:/\b(mot de passe|password)\b/,text:"Si vous avez oublié votre mot de passe, utilisez la réinitialisation depuis la connexion. Si vous êtes déjà connecté, la section Sécurité de votre compte permet de le changer. Ne transmettez jamais votre mot de passe dans ce chat.",href:"/mot-de-passe-oublie",label:"Réinitialiser mon mot de passe",source:"app/(auth)"},
 {topic:"data-rights",match:/\b(supprimer mon compte|effacer mes donnees|exporter mes donnees|export de donnees|suppression du compte)\b/,text:"Votre compte propose une section consacrée aux données personnelles pour demander leur export ou la suppression du compte. Pour une difficulté ou une demande particulière, contactez l’équipe. Le chat ne peut pas supprimer votre compte à votre place.",href:"/contact",label:"Contacter l’équipe",source:"components/gdpr/gdpr-panel.tsx"},
 {topic:"legal",match:/\b(cgu|conditions d utilisation|mentions legales|politique de cookies|conditions legales)\b/,text:"Les liens vers les conditions d’utilisation, la confidentialité et les cookies sont dans le pied de page. Certains textes juridiques sont encore à compléter ; pour une question sur vos droits ou les conditions applicables, l’équipe doit vous répondre personnellement.",href:"/contact",label:"Poser une question à l’équipe",source:"app/(public)/conditions-utilisation/page.tsx"},
 {topic:"search-help",match:/\b(aucun artisan|pas d artisan|aucun resultat|pas de resultat|autre ville|partout en france)\b/,text:"Les résultats dépendent des artisans actifs et de leurs zones d’intervention. Essayez une ville proche ou un autre métier disponible. LaMain2 ne garantit pas la présence d’un artisan dans chaque ville ni une disponibilité immédiate. Si vous ne trouvez personne, l’équipe peut vous aider.",href:"/recherche",label:"Relancer ma recherche",source:"lib/queries/search.ts"},
 {topic:"assistant",match:/\b(robot|automatique|intelligence artificielle|tu es humain|etes vous humain|que peux tu|pouvez vous faire)\b/,text:"Je suis l’assistant automatique de LaMain2. Je peux expliquer la recherche, les réservations, les comptes, les services, le calendrier, les devis et les factures. Je n’ai pas accès à vos données privées et je ne peux pas réserver ou modifier un compte à votre place. Pour une réponse personnelle, je peux transmettre votre demande à l’équipe avec votre accord.",source:"components/chat/chat-widget.tsx"},
];
function answerPlatformQuestion(q: string, previousTopic?: string): ChatAnswer | undefined {
 // Explicit human requests and sensitive disputes still go through the handoff.
 if (/\b(humain|conseiller|litige|rembours[a-z]*|plainte|reclamation|gaz|gas|incendie|electrocution|danger immediat)\b/.test(q) && !/tu es humain|etes vous humain/.test(q)) return;
 const rule = PLATFORM_RULES.find(entry => entry.match.test(q));
 if (rule) return { text:rule.text, href:rule.href, label:rule.label, topic:rule.topic };
 if (previousTopic === "professional" && /^(et )?(mon compte|ou aller|comment commencer)$/.test(q)) return {text:"Ouvrez votre tableau de bord artisan. Vous y retrouvez le profil, les documents, le calendrier et les réservations. L’onglet « Devis et factures » sert à créer vos PDF.",href:"/dashboard",label:"Mon espace artisan",topic:"professional"};
}
