// Website knowledge, kept explicit so the assistant never invents prices or availability.
export type ChatAnswer = { text: string; href?: string; label?: string; topic?: string; handoff?: boolean };
export type ChatCatalog = { cities: {name:string;slug:string}[]; trades: {name:string;name_singular:string;slug_plural:string;active:boolean}[] };
const normal = (text: string) => text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const has = (text: string, pattern: RegExp) => pattern.test(text);
export function answerQuestion(question: string, catalog: ChatCatalog, previousTopic?: string): ChatAnswer {
 const q=normal(question);
 const handoff: ChatAnswer={text:"Je préfère vous orienter vers l’équipe Plan B pour vous donner une réponse fiable. Laissez votre nom et votre email ; vous pourrez aussi ajouter un téléphone pour être rappelé.",handoff:true,topic:"contact"};
 if(has(q,/\b(gaz|gas|incendie|electrocution|danger immediat)\b/)) return {text:"Si vous suspectez un danger immédiat, mettez-vous en sécurité et contactez les secours. Ce chat ne remplace pas un service d’urgence.",handoff:true,topic:"safety"};
 if(has(q,/\b(humain|personne|conseiller|rappel|rappeler|callback|human|reclamation|plainte|rembours[a-z]*|litige|garantie|assurance|probleme|problem)\b/) || has(q,/parler.*(quelqu|equipe|responsable)/)) return handoff;
 if(has(q,/\b(email|mail|telephone|numero|phone)\b/) && has(q,/\b(artisan|plombier|electricien)\b/)) return {text:"Le téléphone de l’artisan est visible sur son profil lorsqu’il est renseigné. Son email reste privé. Ouvrez sa fiche pour l’appeler ou réserver.",href:"/recherche",label:"Trouver son profil",topic:"contact-artisan"};
 if(has(q,/\b(sans (?:creer (?:un |de )?)?compte|sans inscription|sans connexion|sans login|guest|without.*account)\b/)) return {text:"Oui, vous pouvez réserver sans créer de compte. Sur la page de réservation, choisissez de continuer sans connexion, puis indiquez vos coordonnées et les détails de l’intervention. Votre confirmation permet de retrouver votre demande.",href:"/recherche",label:"Choisir un artisan",topic:"guest"};
 if(has(q,/\b(annul|annuler|annulation|modifier|deplacer|cancel|reschedul)/)) return {text:"Avec un compte, retrouvez la réservation dans votre espace client pour l’annuler. Pour changer l’intervention, contactez l’artisan. Si vous avez réservé sans compte, utilisez votre confirmation pour retrouver la demande ; l’équipe peut vous aider si vous ne la retrouvez pas.",href:"/mes-reservations",label:"Mes réservations",topic:"cancellation"};
 if(has(q,/\b(facture|factures|invoice|devis|quote)\b/) && (has(q,/\b(creer|generer|pdf|compte|artisan|download|create|telecharger)\b/) || previousTopic==="professional")) return {text:"Les artisans disposent d’un onglet « Devis et factures » dans leur compte. Ajoutez le client, les prestations et leurs prix, choisissez les dates et le mode de paiement, puis générez un PDF prêt à télécharger. Les coordonnées de votre entreprise sont reprises depuis votre profil.",href:"/devis-factures",label:"Devis et factures",topic:"documents"};
 if(has(q,/\b(devenir|inscrire|inscription|partenaire|abonnement|join)\b/) && has(q,/\b(artisan|professionnel|plombier|electricien|partner)\b/)) return {text:"Créez votre compte artisan, renseignez votre activité et complétez votre dossier. L’équipe vérifie les informations avant l’activation. Votre espace permet ensuite de gérer les prestations, le calendrier, les réservations, les devis et les factures. Pour les conditions d’abonnement, demandez une réponse personnelle à l’équipe.",href:"/inscription/professionnel",label:"Devenir artisan",topic:"professional"};
 if(has(q,/\b(payer|paiement|carte|virement|cash|cheque|payment|pay)\b/)) return {text:"Le paiement de l’intervention se règle directement avec l’artisan. Plan B vous permet de rechercher et réserver ; vérifiez avec le professionnel les moyens de paiement qu’il accepte.",href:"/recherche",label:"Voir les artisans",topic:"payment"};
 if(has(q,/\b(prix|tarif|tarifs|cout|coute|combien|gratuit|commission|price|cost|devis)\b/)) return {text:"La recherche et la réservation sont gratuites pour les clients, sans commission sur l’intervention. Les prix ou la mention « Sur devis » figurent sur les services du profil artisan. Le montant dépend de la prestation : je ne peux pas vous promettre un prix sans ces détails.",href:"/recherche",label:"Comparer les artisans",topic:"pricing"};
 if(has(q,/\b(horaire|horaires|disponible|disponibilites?|heure|ouvert|ferme|hours|available)\b/)) return {text:"Les horaires habituels sont affichés sur le profil de chaque artisan lorsqu’ils sont renseignés. Cliquez sur « Réserver » pour consulter les créneaux proposés. Les horaires habituels ne garantissent pas qu’un créneau est encore libre.",href:"/recherche",label:"Voir les profils et horaires",topic:"hours"};
 if(has(q,/\b(avis|google|review|reviews|note|verifie|fiable|confiance)\b/)) return {text:"Les résultats affichent la note et le nombre d’avis Google renseignés pour chaque artisan. Son profil présente aussi les avis Plan B et un accès à Google Maps pour laisser un avis. Le dossier de l’artisan est vérifié avant l’activation.",href:"/recherche",label:"Consulter les profils",topic:"reviews"};
 if(has(q,/\b(mot de passe|password|connexion|connecter|login|compte|account)\b/)) return {text:"Vous pouvez créer un compte client pour retrouver vos réservations, ou réserver sans connexion. Si vous avez oublié votre mot de passe, utilisez le lien de réinitialisation sur la page de connexion.",href:"/connexion",label:"Accéder à mon compte",topic:"account"};
 if(has(q,/\b(confidentialite|donnee|donnees|cookie|privacy|email prive)\b/)) return {text:"Les emails des artisans ne sont pas affichés publiquement. Pour une réponse personnelle dans ce chat, vos coordonnées et la conversation sont envoyées à l’équipe Plan B uniquement après votre accord.",href:"/confidentialite",label:"Politique de confidentialité",topic:"privacy"};
 const city=catalog.cities.find(c=>(" "+q+" ").includes(" "+normal(c.name)+" "));
 const trade=catalog.trades.find(t=>q.includes(normal(t.name_singular)) || q.includes(normal(t.name)) || (t.slug_plural==="plombiers" && has(q,/\b(fuite|debouchage|plumbing|plumber)\b/)) || (t.slug_plural==="electriciens" && has(q,/\b(electricite|electrician)\b/)));
 if(trade && !trade.active) return {text:trade.name+" n’est pas encore proposé à la réservation sur Plan B. L’équipe peut vous renseigner sur votre besoin.",handoff:true,topic:"search"};
 if(city || trade || has(q,/\b(comment ca marche|fonctionne|chercher|rechercher|trouver|reservation|reserver|book|booking|urgence|urgent)\b/)) {
  const params=new URLSearchParams();if(city)params.set("ville",city.slug);if(trade?.active)params.set("metier",trade.slug_plural);
  return {text:city ? "Voici la recherche pour "+city.name+(trade?" en "+trade.name.toLowerCase():"")+". Comparez les profils, choisissez un service puis un créneau. Les résultats vous indiqueront quels artisans interviennent dans ce secteur." : "Indiquez votre ville et votre métier sur la recherche, comparez les profils puis choisissez une prestation et un créneau. Vous pourrez réserver avec ou sans compte.",href:"/recherche"+(params.size?"?"+params.toString():""),label:city?"Voir les artisans à "+city.name:"Rechercher un artisan",topic:"search"};
 }
 if(has(q,/^(bonjour|bonsoir|salut|hello|hi|coucou)$/)) return {text:"Bonjour ! Je suis l’assistant automatique de Plan B. Vous cherchez un artisan, des informations sur une réservation ou une aide pour votre compte ?",topic:"greeting"};
 if(has(q,/^(merci|merci beaucoup|thanks|thank you|ok|parfait)$/)) return {text:"Avec plaisir ! Vous pouvez me poser une autre question ou demander une réponse personnelle à l’équipe.",topic:previousTopic};
 if(has(q,/^(et sans compte|et sans inscription)$/)) return answerQuestion("sans compte",catalog);
 return handoff;
}
